### ISSUE TITLE
Not showing Jalali date

### ISSUE THREAD

**Issue by ahatashkar** [farajim25/django_admin_rangefilter_jalali#1]
I use your "djano_admin_rangefilter_jalali", but in the rangefilter, the calendar is shown is not Jalali. would you please help me?
tnx

**Comment by farajim25** [comment]
@ahatashkar write your 
python version?
django version?
did you add django_jalali to your project INSTALLED_APPS?

**Comment by ahatashkar** [comment]
Python 3.6.7
django 2.2.2
Also I add 'django_jalali' to my project INSTALLED_APPS.

**Comment by farajim25** [comment]
test 
uninstall package and install 0.4.2.8

pip unintall django-admin-rangefilter-jalali 
pip install django-admin-rangefilter-jalali --no-cache-dir

**Comment by ahatashkar** [comment]
with "pip install django-admin-rangefilter-jalali --no-cache-dir", my problem is solved.

Thank you
